apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  storageClassName: standard  # Specify the StorageClass name if applicable
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /web

    

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis06
spec:
  storageClassName: standard  # Specify the StorageClass name if applicable
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /redis06