apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jekyll-site
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
 




apiVersion: v1     
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi